#!/bin/bash

cd /etc

## Test if the local host is Arch-based

if [ -d /etc/pacman.d ]
then
	## Run the Arch version of update command
	sudo pacman -Syu
fi

## Test if the local host is Debian-based
if [ -d /etc/apt ]
then
	#run debian based
	sudo apt-get update && sudo apt-get dist-updrade -y
fi
